name: Testing
on: push
jobs:
  disco-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Creating required docker services
        run: |
          docker run -dp 6379:6379 redis
          docker run -dp 27017:27017 mongo
      - run: cargo test
        working-directory: ./disco-core
  # disco-vue
  # Carlos should add the testing framework