name: Testing
on: push
jobs:
  disco-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo test
        working-directory: ./disco-core
  # disco-vue
  # Carlos should add the testing framework